version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:8.6.0
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s

  kibana:
    image: kibana:8.6.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: logstash:8.6.0
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy

  log-generator:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
